# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21d4c4f25849c66d38597dd775b814cb952aa8f661fc5dcdbf7a54e32767683845d8f658efd3939b4834f9133c6729e58482c9e7fc33b5e4eded29c1ee848dd0

test:
  secret_key_base: edaab215148dfdff418b965e5e227abfe0b98442a88ba05c51e0ff6cc01dfb80e541e239ddfdd04618aac8cc8d8e2ddfa543b464763b3260442322a303da7257

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
